### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by fduthilleul** [sebw/blog-old.wains.be#3]
The link to https://docs.traefik.io/configuration/backends/docker/ is broken in the following page https://blog.wains.be/2019/2019-01-13-traefik-letsencrypt/

It is probably this page now: https://docs.traefik.io/providers/docker/

**Comment by sebw** [comment]
They have been reshuffling the doc quite a bit. The link you're referring to is completely different.

The broken link used to point to absolutely all possible option in V1.

I'm going to remove the link for the time being and I should write a post about how to get V2 running.
