### ISSUE TITLE
RSS feed support

### ISSUE THREAD

**Issue by ictoi** [sebw/blog-old.wains.be#4]
Would you add RSS feed support so I can follow your blog via my RSS reader?

**Comment by sebw** [comment]
I'll need to investigate Hugo or something else, as Mkdocs doesn't (and won't) support RSS.

**Comment by sebw** [comment]
Website has been migrated to Hugo.

RSS link is now available at https://blog.wains.be/rss/

**Comment by ictoi** [comment]
Thank you so much. Following you now.

Anyway you have an error in the [link](https://blog.wains.be/rss/) you should fix:

| as is | to be |
| -- | -- |
| https://hugo.wains.be/index.xml | https://blog.wains.be/index.xml |

found the correct link via [view-source:https://blog.wains.be/](view-source:https://blog.wains.be/) > "alternate" tag.

**Comment by sebw** [comment]
Ah, good catch, that was the preprod URL :-)

It's now fixed and live!

Thanks for the request, RSS was a big problem with Mkdocs, but search was a problem with Hugo. I figured it out and the new site now has both :-)
